partbin:
  upload:
    directory: ./app/uploads/products
    max-images-per-product: 10
    allowed-types: jpg,jpeg,png,webp
    max-file-size: 10MB
spring:
  config:
    import: file:.env[.properties]
  application:
    name: partbin
  datasource:
    url: jdbc:${DATABASE_URL} # Example: jdbc:postgresql://localhost:5432/partbin
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: file:./app/uploads/, classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 86400000
springdoc:
  swagger-ui:
    path: "/doc"
